package br.cefetrn.smartproject.smartinterface.Guis;
//1.2
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.io.PipedInputStream;
import java.io.PipedOutputStream;
import java.io.PrintStream;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.smartcardio.CardException;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.DefaultTableModel;


/*
 * GuiGerenciamentoCartao.java
 *
 * Created on 23 de Setembro de 2007, 09:56
 */
import javax.swing.table.TableColumn;

import br.cefetrn.smartproject.smartinterface.SmartInterface;
import br.cefetrn.smartproject.smartinterface.beans.Arquivo;
import br.cefetrn.smartproject.smartinterface.beans.CardApplet;
import br.cefetrn.smartproject.smartinterface.beans.CardManager;
import br.cefetrn.smartproject.smartinterface.util.ReaderThread;



/**
 *
 * @author  Gleison
 */
public class GuiGerenciamentoCartao extends javax.swing.JFrame {
    
	 // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExcluirApplet;
    private javax.swing.JButton jButtonExcluirArquivo;
    private javax.swing.JButton jButtonExecutarAPDU;
    private javax.swing.JButton jButtonInstalar;
    private javax.swing.JButton jButtonProcurarCAP;
    private javax.swing.JButton jButtonSelecionarApplet;
    private javax.swing.JLabel jLabelAPDUExec;
    private javax.swing.JLabel jLabelApplets;
    private javax.swing.JLabel jLabelArquivos;
    private javax.swing.JLabel jLabelCAP;
    private javax.swing.JLabel jLabelCardManager;
    private javax.swing.JLabel jLabelCardManagerID;
    private javax.swing.JMenu jMenuAjuda;
    private javax.swing.JMenu jMenuArquivo;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuEditar;
    private javax.swing.JMenu jMenuExibir;
    private javax.swing.JMenuItem jMenuItemAbrir;
    private javax.swing.JMenuItem jMenuItemColar;
    private javax.swing.JMenuItem jMenuItemComandos;
    private javax.swing.JMenuItem jMenuItemCopiar;
    private javax.swing.JMenuItem jMenuItemNovoCAP;
    private javax.swing.JMenuItem jMenuItemRecortar;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuItemSobre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelConsole;
    private javax.swing.JScrollPane jScrollPaneConsole;
    private javax.swing.JScrollPane jScrollPaneApplets;
    private javax.swing.JScrollPane jScrollPaneArquivos;
    private javax.swing.JSplitPane jSplitPaneApplets_Arquivos;
    private javax.swing.JTabbedPane jTabbedPaneCOnsole;
    private javax.swing.JTable jTableApplets;
    private javax.swing.JTable jTableArquivos;
    private javax.swing.JTextArea jTextAreaConsole;
    private javax.swing.JTextField jTextFieldAPDU;
    private javax.swing.JTextField jTextFieldCAPPath;
    private javax.swing.JToolBar jToolBar;
    private JButton jButtonLimparConsole;
    
    private SmartInterface smartInterface;
    
    // End of variables declaration//GEN-END:variables
	public static void main(String[] args){
		GuiGerenciamentoCartao gui = new GuiGerenciamentoCartao();
		gui.setVisible(true);
	}
	
	public GuiGerenciamentoCartao(){
		configurarLookAndFeel();
        this.setIconImage(new ImageIcon(getClass().getClassLoader().getResource("imagens/javaCard.jpg")).getImage());
        initComponents();
        setarContentPane();
        //this.criarConsole();
        configurarTabelas(jTableApplets);
        configurarTabelas(jTableArquivos);
	}
	
    /** Creates new form GuiGerenciamentoCartao 
     * @throws CardException */
    public GuiGerenciamentoCartao(SmartInterface smartInterface) throws CardException {
    	
    	this.smartInterface = smartInterface;
    	
        configurarLookAndFeel();
        this.setIconImage(new ImageIcon(getClass().getClassLoader().getResource("imagens/javaCard.jpg")).getImage());
        initComponents();
        this.iniciarDados();
        setarContentPane();
        this.criarConsole();
        configurarTabelas(jTableApplets);
        configurarTabelas(jTableArquivos);
    }

    private void iniciarDados() throws CardException{
    	this.listarApplets();
    	this.listarArquivos();
    	this.listarCardManager();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    
    private void eventoBotaoExcluirArquivo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventoBotaoExcluirArquivo
    		try {
				this.exluirArquivo();
			} catch (CardException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
    }

	private void eventoBotaoInstalarCAP(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventoBotaoInstalarCAP
		try {
			GuiGerenciamentoCartao.this.instalarApplet();
		} catch (CardException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	private void eventoBotaoProcurarCAP(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventoBotaoProcurarCAP
		this.procurarCAP();		 
	}
	
	private void eventoBotaoExecutarAPDU(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventoBotaoExecutarAPDU
    
	}
	
	 private void eventoBotaoLimparConsole(java.awt.event.ActionEvent evt) {
	    	this.jTextAreaConsole.setText("");
	}
	
	private void eventoBotaoSelecionarApplet(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventoBotaoSelecionarApplet
		try {
			this.selecionarApplet();
		} catch (CardException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}   
	}

	private void eventoBotaoExcluirApplet(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventoBotaoExcluirApplet
		try {
			this.exluirApplet();
		} catch (CardException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	private void eventoMenuItemSobre(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventoMenuItemSobre
    
	}

	private void eventoMenuItemComandos(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventoMenuItemComandos
    
	}

	private void eventoMenuItemRecortar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventoMenuItemRecortar
    
	}

	private void eventoMenuItemColar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventoMenuItemColar
    
	}

	private void eventoMenuItemCopiar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventoMenuItemCopiar
    
	}

	private void eventoMenuItemSair(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventoMenuItemSair
    
	}

	private void eventoMenuItemNovoCAP(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventoMenuItemNovoCAP
		
	}
	
	private void EventoMenuItemAbrir(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EventoMenuItemAbrir
    
	}
    
        
    private void configurarTabelas(JTable tabela){
        //coluna ordem
        tabela.getColumnModel().getColumn(0).setMaxWidth(40);
        tabela.getColumnModel().getColumn(0).setMinWidth(40);
       
        //coluna ID
        tabela.getColumnModel().getColumn(1).setMinWidth(290);
        
        //Coluna estado
        tabela.getColumnModel().getColumn(2).setMinWidth(110);
        tabela.getColumnModel().getColumn(2).setMaxWidth(120);       
    }
    
    private void configurarLookAndFeel() {
       try {
			javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
		} catch(Exception e) {
			e.printStackTrace();
		}
      
    }
    
    private void setarContentPane(){
         this.setContentPane(jPanel5);
         
    }
    
    public void criarConsole(){
        try {
            PipedInputStream piOut;
            PipedInputStream piErr;
            PipedOutputStream poOut;
            PipedOutputStream poErr;

            // Configura System.out
            piOut = new java.io.PipedInputStream();
            poOut = new java.io.PipedOutputStream(piOut);
            java.lang.System.setOut(new java.io.PrintStream(poOut, true));

            // Configura System.err
            piErr = new java.io.PipedInputStream();
            poErr = new java.io.PipedOutputStream(piErr);
            java.lang.System.setErr(new java.io.PrintStream(poErr, true));

            // Cria as threads de leitura
            new ReaderThread(piOut, this.jTextAreaConsole).start();
            new ReaderThread(piErr, this.jTextAreaConsole).start();
            
        } catch (IOException ex) {
            Logger.getLogger("global").log(Level.SEVERE, null, ex);
        }
        
    
        
    }
    
    public void listarApplets() throws CardException{
    	
    	ArrayList<CardApplet> applets = new ArrayList<CardApplet>();
    	
    	try {
			applets = this.smartInterface.listarApplets();
		
    	} catch ( Exception e) {
			e.printStackTrace();
		} 
		int i=1;
		for(CardApplet applet : applets){
			
			DefaultTableModel tabelaAppletsModel = (DefaultTableModel)this.jTableApplets.getModel();
			
			String id = applet.getId();
			String estado = applet.getEstado();
			
			tabelaAppletsModel.insertRow(i-1, new String[]{""+i, id, estado});
			++i;
		}
    }
    
    public void listarArquivos() throws CardException{
    	ArrayList<Arquivo> arquivos = new ArrayList<Arquivo>();
    	
    	
			try {
				arquivos = this.smartInterface.listarArquivos();
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			
		
		int i = 1;
		for(Arquivo arquivo : arquivos){
			DefaultTableModel tabelaArquivosModel = (DefaultTableModel)this.jTableArquivos.getModel();
			
			String id = arquivo.getId();
			String estado = arquivo.getEstado();
			
			tabelaArquivosModel.insertRow(i-1, new String[]{""+i, id, estado});
			++i;
		}
    	
    }
    
    public void listarCardManager() throws CardException{
    	
    	CardManager cardManager = null;
    	
    	
    		
			try {
				cardManager = this.smartInterface.listarCardManager();
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			
		
		
		String id = cardManager.getId();
		String estado = cardManager.getEstado();
		
		this.jLabelCardManagerID.setText("ID: "+id+"       Estado: "+estado);
		
    }
    
    public void selecionarApplet() throws CardException{
    	
    	 String id = new String();
    	 int row = this.jTableApplets.getSelectedRow();
    	 id = (String)this.jTableApplets.getValueAt(row, 1);    	 
    	 boolean selecionou = this.smartInterface.selecionarApplet(id);
    	 if(selecionou){
    		 JOptionPane.showMessageDialog(this, "Applet selecionado com sucesso!");
    	 }
    	 else{
    		 JOptionPane.showMessageDialog(this, "O Applet não pode ser selecionado. " +
    		 		"Para mais detalhes, verifique a saída do console");
    	 }
    	 
    }
    
    private void procurarCAP(){
    	
    	JFileChooser fileChooser = new JFileChooser();
            	
    	FileNameExtensionFilter filter = new FileNameExtensionFilter("Arquivo CAP", "cap");
    	fileChooser.setFileFilter(filter);    	
        fileChooser.setFileFilter(filter);
        fileChooser.setDialogTitle("Selecione o arquivo CAP");
        int valorRetornado = fileChooser.showOpenDialog(this);
        
        if(valorRetornado == JFileChooser.APPROVE_OPTION){
        	jTextFieldCAPPath.setText(fileChooser.getSelectedFile().getAbsolutePath());
        }
    	
     }
 
    public void instalarApplet() throws CardException{
    	String capPath = this.jTextFieldCAPPath.getText();
    	
    	
    	
    	try {
    		
			this.smartInterface.instalarApplet(capPath);
			
		} catch (IOException e) {
			e.printStackTrace();
		}
		JOptionPane.showMessageDialog(this, "Verifique a saída do console para visualizar o resultado da tentativa de instalação");
			
    }
    
    private void exluirApplet() throws CardException {
    	
   	 String id = new String();
   	 int row = this.jTableApplets.getSelectedRow();
   	 id = (String)this.jTableApplets.getValueAt(row, 1);   	 
   	 boolean excluiu;
   	 try {
   		excluiu = this.smartInterface.excluirApplet(id);
   		if(excluiu){
   			this.removerLinhaTabela(this.jTableApplets, row);
   			JOptionPane.showMessageDialog(this, "Applet excluído com sucesso!");
   		}
   		else{
   			JOptionPane.showMessageDialog(this, "O Applet não pode ser excluído." +
				" Verifique a saida do console para mais detalhes");
   		}
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();			
		}
		
	}
    
    private void exluirArquivo() throws CardException {
    	
      	 String id = new String();
      	 int row = this.jTableArquivos.getSelectedRow();
      	 id = (String)this.jTableArquivos.getValueAt(row, 1);      	 
      	 boolean excluiu;
      	 try {
   			excluiu = this.smartInterface.excluirArquivo(id);
   			if(excluiu){
   				this.removerLinhaTabela(this.jTableArquivos, row);
   				JOptionPane.showMessageDialog(this, "Arquivo excluído com sucesso!");
   			}
   			else{
   				JOptionPane.showMessageDialog(this, "O Arquivo nao pode ser excluído." +
   						" Verifique a saida do console para mais detalhes");
   			}
   		} catch (IOException e) {
   			// TODO Auto-generated catch block
   			e.printStackTrace();
   		}
   		
   	}
    
    public void removerLinhaTabela(JTable tabela, int row){
    	DefaultTableModel tabelaArquivosModel = (DefaultTableModel)tabela.getModel();
    	tabelaArquivosModel.removeRow(row);
    }
    
    
//******************************************************************************************    
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jSplitPaneApplets_Arquivos = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jLabelApplets = new javax.swing.JLabel();
        jScrollPaneApplets = new javax.swing.JScrollPane();
        jTableApplets = new javax.swing.JTable();
        jButtonInstalar = new javax.swing.JButton();
        jButtonExcluirApplet = new javax.swing.JButton();
        jButtonSelecionarApplet = new javax.swing.JButton();
        jLabelAPDUExec = new javax.swing.JLabel();
        jTextFieldAPDU = new javax.swing.JTextField();
        jButtonExecutarAPDU = new javax.swing.JButton();
        jLabelCAP = new javax.swing.JLabel();
        jTextFieldCAPPath = new javax.swing.JTextField();
        jButtonProcurarCAP = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPaneArquivos = new javax.swing.JScrollPane();
        jTableArquivos = new javax.swing.JTable();
        jLabelArquivos = new javax.swing.JLabel();
        jButtonExcluirArquivo = new javax.swing.JButton();
        jTabbedPaneCOnsole = new javax.swing.JTabbedPane();
        jPanelConsole = new javax.swing.JPanel();
        jScrollPaneConsole = new javax.swing.JScrollPane();
        jTextAreaConsole = new javax.swing.JTextArea();
        jButtonLimparConsole = new javax.swing.JButton();
        jLabelCardManager = new javax.swing.JLabel();
        jLabelCardManagerID = new javax.swing.JLabel();
        jToolBar = new javax.swing.JToolBar();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuArquivo = new javax.swing.JMenu();
        jMenuItemAbrir = new javax.swing.JMenuItem();
        jMenuItemNovoCAP = new javax.swing.JMenuItem();
        jMenuItemSair = new javax.swing.JMenuItem();
        jMenuEditar = new javax.swing.JMenu();
        jMenuItemCopiar = new javax.swing.JMenuItem();
        jMenuItemColar = new javax.swing.JMenuItem();
        jMenuItemRecortar = new javax.swing.JMenuItem();
        jMenuExibir = new javax.swing.JMenu();
        jMenuAjuda = new javax.swing.JMenu();
        jMenuItemComandos = new javax.swing.JMenuItem();
        jMenuItemSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Smart Interface :: Gerenciamento do Cart\u00e3o");
        setBounds(new java.awt.Rectangle(0, 0, 1024, 760));
        setMinimumSize(new java.awt.Dimension(800, 0));

        jSplitPaneApplets_Arquivos.setDividerLocation(490);

        jLabelApplets.setFont(new java.awt.Font("Arial", 1, 14));
        jLabelApplets.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelApplets.setText("APPLETS");

        jTableApplets.setFont(new java.awt.Font("Arial", 0, 12));
        jTableApplets.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "", "ID", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPaneApplets.setViewportView(jTableApplets);

        jButtonInstalar.setFont(new java.awt.Font("Arial", 0, 12));
        jButtonInstalar.setText("Instalar");
        jButtonInstalar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventoBotaoInstalarCAP(evt);
            }
        });

        jButtonExcluirApplet.setFont(new java.awt.Font("Arial", 0, 12));
        jButtonExcluirApplet.setText("Excluir");
        jButtonExcluirApplet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventoBotaoExcluirApplet(evt);
            }
        });

        jButtonSelecionarApplet.setFont(new java.awt.Font("Arial", 0, 12));
        jButtonSelecionarApplet.setText("Selecionar");
        jButtonSelecionarApplet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventoBotaoSelecionarApplet(evt);
            }
        });

        jLabelAPDUExec.setFont(new java.awt.Font("Arial", 0, 12));
        jLabelAPDUExec.setText("APDU a executar:");

        jButtonExecutarAPDU.setFont(new java.awt.Font("Arial", 0, 12));
        jButtonExecutarAPDU.setText("Executar");
        jButtonExecutarAPDU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventoBotaoExecutarAPDU(evt);
            }
        });

        jLabelCAP.setFont(new java.awt.Font("Arial", 0, 12));
        jLabelCAP.setText("Arquivo CAP:");

        jButtonProcurarCAP.setFont(new java.awt.Font("Arial", 0, 12));
        jButtonProcurarCAP.setText("Procurar");
        jButtonProcurarCAP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventoBotaoProcurarCAP(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelApplets, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneApplets, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(308, Short.MAX_VALUE)
                .addComponent(jButtonSelecionarApplet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonExcluirApplet)
                .addGap(30, 30, 30))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCAP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextFieldCAPPath, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonProcurarCAP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonInstalar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelAPDUExec)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldAPDU, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonExecutarAPDU)
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabelApplets, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneApplets, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSelecionarApplet)
                    .addComponent(jButtonExcluirApplet))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonExecutarAPDU)
                    .addComponent(jTextFieldAPDU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAPDUExec))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonInstalar)
                    .addComponent(jButtonProcurarCAP)
                    .addComponent(jTextFieldCAPPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCAP))
                .addGap(22, 22, 22))
        );

        jSplitPaneApplets_Arquivos.setLeftComponent(jPanel1);

        jTableArquivos.setFont(new java.awt.Font("Arial", 0, 12));
        jTableArquivos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "", "ID", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPaneArquivos.setViewportView(jTableArquivos);

        jLabelArquivos.setFont(new java.awt.Font("Arial", 1, 14));
        jLabelArquivos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelArquivos.setText("ARQUIVOS");

        jButtonExcluirArquivo.setFont(new java.awt.Font("Arial", 0, 12));
        jButtonExcluirArquivo.setText("Excluir Selecionado");
        jButtonExcluirArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventoBotaoExcluirArquivo(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jScrollPaneArquivos, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                            .addGap(10, 10, 10))
                        .addComponent(jLabelArquivos, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonExcluirArquivo)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabelArquivos, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneArquivos, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonExcluirArquivo)
                .addGap(22, 22, 22))
        );

        jSplitPaneApplets_Arquivos.setRightComponent(jPanel2);

        jTabbedPaneCOnsole.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPaneCOnsole.setFont(new java.awt.Font("Arial", 0, 12));

        jPanelConsole.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPaneConsole.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(213, 212, 205)));

        jTextAreaConsole.setColumns(20);
        jTextAreaConsole.setLineWrap(true);
        jTextAreaConsole.setEditable(false);
        jTextAreaConsole.setRows(5);
        
        jScrollPaneConsole.setViewportView(jTextAreaConsole);
        jScrollPaneConsole.setBorder(null);

        jButtonLimparConsole.setFont(new java.awt.Font("Arial", 0, 12));
        jButtonLimparConsole.setText("Limpar");
        jButtonLimparConsole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventoBotaoLimparConsole(evt);
            }
        });

        javax.swing.GroupLayout jPanelConsoleLayout = new javax.swing.GroupLayout(jPanelConsole);
        jPanelConsole.setLayout(jPanelConsoleLayout);
        jPanelConsoleLayout.setHorizontalGroup(
            jPanelConsoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelConsoleLayout.createSequentialGroup()
                .addComponent(jScrollPaneConsole, javax.swing.GroupLayout.DEFAULT_SIZE, 904, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonLimparConsole)
                .addContainerGap())
        );
        jPanelConsoleLayout.setVerticalGroup(
            jPanelConsoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsoleLayout.createSequentialGroup()
                .addComponent(jButtonLimparConsole)
                .addContainerGap())
            .addComponent(jScrollPaneConsole, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
        );

        jTabbedPaneCOnsole.addTab("Console", jPanelConsole);

        jLabelCardManager.setFont(new java.awt.Font("Arial", 1, 24));
        jLabelCardManager.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCardManager.setText("CARD MANAGER");

        jLabelCardManagerID.setFont(new java.awt.Font("Arial", 1, 18));
        jLabelCardManagerID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCardManagerID.setText("ID e Estado");

        jToolBar.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jToolBar.setRollover(true);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPaneApplets_Arquivos, javax.swing.GroupLayout.DEFAULT_SIZE, 980, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jTabbedPaneCOnsole, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
            .addComponent(jToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCardManager, javax.swing.GroupLayout.DEFAULT_SIZE, 980, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCardManagerID, javax.swing.GroupLayout.DEFAULT_SIZE, 980, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jLabelCardManager)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCardManagerID)
                .addGap(18, 18, 18)
                .addComponent(jSplitPaneApplets_Arquivos, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPaneCOnsole, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenuArquivo.setText("Arquivo");
        jMenuArquivo.setFont(new java.awt.Font("Arial", 0, 12));

        jMenuItemAbrir.setFont(new java.awt.Font("Arial", 0, 12));
        jMenuItemAbrir.setText("Abrir");
        jMenuItemAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EventoMenuItemAbrir(evt);
            }
        });
        jMenuArquivo.add(jMenuItemAbrir);

        jMenuItemNovoCAP.setFont(new java.awt.Font("Arial", 0, 12));
        jMenuItemNovoCAP.setText("Novo CAP");
        jMenuItemNovoCAP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventoMenuItemNovoCAP(evt);
            }
        });
        jMenuArquivo.add(jMenuItemNovoCAP);

        jMenuItemSair.setFont(new java.awt.Font("Arial", 0, 12));
        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventoMenuItemSair(evt);
            }
        });
        jMenuArquivo.add(jMenuItemSair);

        jMenuBar.add(jMenuArquivo);

        jMenuEditar.setText("Editar");
        jMenuEditar.setFont(new java.awt.Font("Arial", 0, 12));

        jMenuItemCopiar.setFont(new java.awt.Font("Arial", 0, 12));
        jMenuItemCopiar.setText("Copiar");
        jMenuItemCopiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventoMenuItemCopiar(evt);
            }
        });
        jMenuEditar.add(jMenuItemCopiar);

        jMenuItemColar.setFont(new java.awt.Font("Arial", 0, 12));
        jMenuItemColar.setText("Colar");
        jMenuItemColar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventoMenuItemColar(evt);
            }
        });
        jMenuEditar.add(jMenuItemColar);

        jMenuItemRecortar.setFont(new java.awt.Font("Arial", 0, 12));
        jMenuItemRecortar.setText("Recortar");
        jMenuItemRecortar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventoMenuItemRecortar(evt);
            }
        });
        jMenuEditar.add(jMenuItemRecortar);

        jMenuBar.add(jMenuEditar);

        jMenuExibir.setText("Exibir");
        jMenuExibir.setFont(new java.awt.Font("Arial", 0, 12));
        jMenuBar.add(jMenuExibir);

        jMenuAjuda.setText("Ajuda");
        jMenuAjuda.setFont(new java.awt.Font("Arial", 0, 12));

        jMenuItemComandos.setFont(new java.awt.Font("Arial", 0, 12));
        jMenuItemComandos.setText("Comandos");
        jMenuItemComandos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventoMenuItemComandos(evt);
            }
        });
        jMenuAjuda.add(jMenuItemComandos);

        jMenuItemSobre.setText("Sobre");
        jMenuItemSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventoMenuItemSobre(evt);
            }
        });
        jMenuAjuda.add(jMenuItemSobre);

        jMenuBar.add(jMenuAjuda);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

   
    
}
