/*
 * PesquisarFuncionario2.java
 *
 * Created on January 24, 2007, 9:11 AM
 */

package br.cefetrn.smartcefet.visao;

import br.cefetrn.smartcefet.SmartCEFET;
import br.cefetrn.smartcefet.dominio.FuncionarioSistema;
import br.cefetrn.smartproject.gpcomm.GpCommException;

import java.util.List;
import javax.persistence.NoResultException;
import javax.swing.JOptionPane;

/**
 *
 * @author  cd1
 */
public class PesquisarFuncionario extends javax.swing.JDialog {
    
	private SmartCEFET smartCEFET;
	
    /** Creates new form PesquisarFuncionario2 */
    public PesquisarFuncionario(ConfigurarCartao parent) {
        super(parent, true);
        initComponents();
        getRootPane().setDefaultButton(bPesquisar);
        try {
			smartCEFET = new SmartCEFET();
		} catch (GpCommException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        lMatricula = new javax.swing.JLabel();
        lNome = new javax.swing.JLabel();
        tfMatricula = new javax.swing.JTextField();
        tfNome = new javax.swing.JTextField();
        bPesquisar = new javax.swing.JButton();
        spFuncionarios = new javax.swing.JScrollPane();
        //FIXME ver essa classe
        tFuncionarios = new FuncionarioSistemaTable();
        separador = new javax.swing.JSeparator();
        bFechar = new javax.swing.JButton();
        bSelecionar = new javax.swing.JButton();

        FormListener formListener = new FormListener();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pesquisar funcion\u00e1rios");
        setLocationByPlatform(true);

        lMatricula.setText("Matr\u00edcula:");

        lNome.setText("Nome:");

        bPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/find.png")));
        bPesquisar.setText("Pesquisar");
        bPesquisar.addActionListener(formListener);

        spFuncionarios.setViewportView(tFuncionarios);

        bFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exit.png")));
        bFechar.setText("Fechar");
        bFechar.addActionListener(formListener);

        bSelecionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ok.png")));
        bSelecionar.setText("Selecionar");
        bSelecionar.addActionListener(formListener);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(separador, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
                    .addComponent(spFuncionarios, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lMatricula)
                            .addComponent(lNome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfNome, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bPesquisar))
                            .addComponent(tfMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bSelecionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bFechar)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {bFechar, bSelecionar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lMatricula)
                    .addComponent(tfMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNome)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spFuncionarios, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bFechar)
                    .addComponent(bSelecionar))
                .addContainerGap())
        );

        pack();
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.ActionListener {
        FormListener() {}
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            if (evt.getSource() == bPesquisar) {
                PesquisarFuncionario.this.bPesquisarActionPerformed(evt);
            }
            else if (evt.getSource() == bFechar) {
                PesquisarFuncionario.this.bFecharActionPerformed(evt);
            }
            else if (evt.getSource() == bSelecionar) {
                PesquisarFuncionario.this.bSelecionarActionPerformed(evt);
            }
        }
    }// </editor-fold>//GEN-END:initComponents

private void bSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSelecionarActionPerformed
    FuncionarioSistemaTableModel modelo =
                (FuncionarioSistemaTableModel) tFuncionarios.getModel();
    if (tFuncionarios.getSelectedRowCount() == 0) {
        JOptionPane.showMessageDialog(this, "Selecione um funcionário.",
                "Funcionário não selecionado", JOptionPane.WARNING_MESSAGE);
    }
    else {
        FuncionarioSistema f = modelo.getFuncionario(
                tFuncionarios.getSelectedRow());
        ConfigurarCartao configurar = (ConfigurarCartao) getParent();
        configurar.setMatricula(f.getMatricula());
        configurar.setFuncionario(f);
        dispose();
    }
}//GEN-LAST:event_bSelecionarActionPerformed

private void bPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPesquisarActionPerformed
    String matricula = tfMatricula.getText();
    String nome = tfNome.getText();
    if ("".equals(matricula) && "".equals(nome)) {
        JOptionPane.showMessageDialog(this, "Preencha a matrícula ou o nome " +
                "do funcionário.", "Campos vazios",
                JOptionPane.WARNING_MESSAGE);
        tfMatricula.requestFocusInWindow();
    }
    else {
        FuncionarioSistemaTableModel modelo =
                    ((FuncionarioSistemaTableModel) tFuncionarios.getModel());
        if ("".equals(matricula)) {
            List<FuncionarioSistema> funcionarios =
            	this.smartCEFET.recuperarFuncionariosPorNome(nome);
            modelo.setFuncionarios(funcionarios);
        }
        else {
            FuncionarioSistema funcionario = null;
            try {
                funcionario = this.smartCEFET.recuperarFuncionarioPorMatricula(matricula);
            }
            catch (NoResultException e) {
                // nada
            }
            modelo.setFuncionario(funcionario);
        }
    }
}//GEN-LAST:event_bPesquisarActionPerformed

private void bFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFecharActionPerformed
    dispose();
}//GEN-LAST:event_bFecharActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bFechar;
    private javax.swing.JButton bPesquisar;
    private javax.swing.JButton bSelecionar;
    private javax.swing.JLabel lMatricula;
    private javax.swing.JLabel lNome;
    private javax.swing.JSeparator separador;
    private javax.swing.JScrollPane spFuncionarios;
    private javax.swing.JTable tFuncionarios;
    private javax.swing.JTextField tfMatricula;
    private javax.swing.JTextField tfNome;
    // End of variables declaration//GEN-END:variables
    
}
